---
- name: Upgrade
  hosts: all
  strategy: free
  become: true
  force_handlers: true
  vars:
    ansible_python_interpreter: /usr/libexec/platform-python
  tasks:
    - name: Perform OS upgrade
      block:
        - name: Leapp upgrade
          ansible.builtin.import_role:
            name: upgrade
            tasks_from: leapp-post-upgrade-crypto
...
