---
- name: Roleback
  hosts: all
  strategy: free
  become: true
  force_handlers: true
  tasks:
    - name: Initialize lock and logging
      ansible.builtin.import_role:
        name: logging
      vars:
        job_name: 'RIPU LVM snapshot rollback'

    - name: Perform LVM snapshot rollback
      block:
        - name: Snapshot rollback
          ansible.builtin.import_role:
            name: rollback

# always:
#   - name: Clean up
#     ansible.builtin.import_role:
#       name: logging
#       tasks_from: clean_up.yml
...
