---
- name: Take snapshot of instance
  hosts: all
  connection: local
  gather_facts: false
  tasks:
    - name: Take snapshot of instances in region "{{ ec2_region }}"
      ansible.builtin.include_role:
        name: snapshot
      vars:
        ec2_instance_action: "snapshot_create"
...
