---
- name: "Register to leapp activation key"
  ansible.builtin.include_tasks: register-activation-key.yml
  when: leapp_upgrade_type == 'disconnected'

- name: Register output of 'yum repolist'
  ansible.builtin.shell: |
    set -o pipefail
    yum repolist
  args:
    executable: /bin/bash
  register: yum_repolist
  changed_when: yum_repolist.rc != 0

# Determine if node is an EC2 Marketplace instance utilzing RHUI
- name: Set fact for RHUI RHEL extras repo name when EC2 and utilizing RHUI
  ansible.builtin.set_fact:
    analysis_repos_el7: "rhel-7-server-rhui-extras-rpms"
  when:
    - ansible_system_vendor == "Amazon EC2" or ansible_system_vendor == "Xen"
    - ansible_product_uuid|regex_search('^ec2') or ansible_product_uuid|regex_search('^EC2')
    - "'rhui' in yum_repolist.stdout"
    - ansible_distribution_major_version|int == 7

- name: Ensure Leapp metadata is available for disconnected or RHUI Marketplace Leapp upgrades
  when: |
    leapp_upgrade_type == 'disconnected' or
    (ansible_system_vendor == "Amazon EC2" and (ansible_product_uuid|regex_search('^ec2') or ansible_product_uuid|regex_search('^EC2')) and "'rhui' in yum_repolist.stdout") or
    (ansible_system_vendor == "Xen" and (ansible_product_uuid|regex_search('^ec2') or ansible_product_uuid|regex_search('^EC2')) and "'rhui' in yum_repolist.stdout")
  block:
    - name: /etc/leapp/files directory exists
      ansible.builtin.file:
        path: /etc/leapp/files
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Leapp utility metadata is installed
      ansible.builtin.unarchive:
        src: "{{ leapp_metadata_url }}"
        dest: /etc/leapp/files
        remote_src: true
        owner: root
        group: root

- name: Ensure leapp log directory exists
  ansible.builtin.file:
    path: /var/log/leapp
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Install packages for preupgrade analysis on RHEL 7
  ansible.builtin.package:
    name: "{{ analysis_packages_el7 }}"
    enablerepo: "{{ analysis_repos_el7 }}"
    state: latest
  when: ansible_distribution_major_version|int == 7

- name: Install leapp-rhui-aws package for preupgrade analysis for RHUI Marketplace Leapp upgrades
  ansible.builtin.yum:
    name: leapp-rhui-aws
    state: latest
  when:
    - ansible_system_vendor == "Amazon EC2" or ansible_system_vendor == "Xen"
    - ansible_product_uuid|regex_search('^ec2') or ansible_product_uuid|regex_search('^EC2')
    - "'rhui' in yum_repolist.stdout"

- name: Install packages for preupgrade analysis on RHEL 8
  ansible.builtin.package:
    name: "{{ analysis_packages_el8 }}"
    state: latest
  when: ansible_distribution_major_version|int == 8

- name: Populate leapp_answers file
  ansible.builtin.copy:
    content: "{{ leapp_answerfile }}"
    dest: /var/log/leapp/answerfile
    owner: root
    group: root
    mode: '0644'
  when: leapp_answerfile is defined

- name: Leapp preupgrade report
  ansible.builtin.shell: >
    set -o pipefail;
    leapp preupgrade
    {{ leapp_preupg_opts }}
    {{ leapp_enable_repos_args }}
    2>&1 | tee -a {{ log_file }}
  register: leapp
  args:
    executable: /bin/bash
  async: 43200
  poll: 60
  failed_when: "'report has been generated' not in leapp.stdout"

- name: Result file status
  ansible.builtin.stat:
    path: "{{ result_filename }}"
  register: result

- name: Check that result file exists
  ansible.builtin.assert:
    that: result.stat.exists
    msg: "The preupgrade analysis report file {{ result_filename }} was not created."

- name: Include the parse_leapp_report role to check for inhibitors
  ansible.builtin.include_role:
    name: infra.leapp.parse_leapp_report

- name: Preupgrade analysis report is done
  ansible.builtin.debug:
    msg: >-
      The preupgrade analysis report generation is now complete.
      {{ 'WARNING: Inhibitors' if upgrade_inhibited else 'SUCCESS: No inhibitors' }} found.
      Review the result file at {{ result_filename }}.
...
